// Thin wrappers around the Wails-generated bindings in ../wailsjs/go/main/App
// (generated by `wails dev` / `wails build` — not checked in, see .gitignore).
// Keeping every backend call behind this module means the rest of the
// frontend never imports wailsjs directly.
import * as Backend from "../wailsjs/go/main/App";
import { EventsOn } from "../wailsjs/runtime/runtime";

export interface Settings {
  lastAppName: string;
  theme: string;
  rememberSecrets: boolean;
}

export interface SecretsBundle {
  sqlUser: string;
  sqlPassword: string;
  gpgPassphrase: string;
  extraEnv: ExtraEnvVar[];
}

// loadSecrets returns both possible sources unmerged, rather than picking a
// winner, so the GUI can offer a choice when both an environment variable
// and a keyring entry exist for the same secret (and disagree).
export interface LoadedSecrets {
  env: SecretsBundle;
  keyring: SecretsBundle;
}

// A pre-deploy key check saved as SECRET_CHECK_<name> in deploy.conf. name is
// the EXTRA_ENV_VARS entry without its '+'; spec is "URL|Header: value|...".
export interface SecretCheckEntry {
  name: string;
  spec: string;
}

export interface DeployConf {
  appName: string;
  envVarPrefix: string;
  dbName: string;
  httpPort: string;
  gitRepo: string;
  gitUpstream: string;
  gitBranch: string;
  dropletRegion: string;
  dropletImage: string;
  dropletSize: string;
  extraEnvVars: string;
  secretChecks: SecretCheckEntry[];
}

export interface DeployConfResult {
  found: boolean;
  conf: DeployConf;
}

export interface CheckResult {
  name: string;
  ok: boolean;
  detail: string;
}

export interface PreflightResult {
  wslBlocking: boolean;
  checks: CheckResult[];
}

export interface LogLine {
  appName: string;
  stream: "stdout" | "stderr";
  text: string;
}

export interface ExitInfo {
  appName: string;
  code: number;
  err?: string;
}

export interface StatusResult {
  dropletExists: boolean;
  appExists: boolean;
  appURL: string;
}

export interface UpdateInfo {
  available: boolean;
  version: string;
}

// Month-to-date usage for the whole DO account (amounts are DO's decimal
// strings, USD). generatedAt is when DO last computed it, not "now".
export interface BalanceResult {
  monthToDateUsage: string;
  accountBalance: string;
  generatedAt: string;
}

export interface TierOption {
  number: number;
  slug: string;
  appSize: string;
  label: string;
}

export interface RegionOption {
  slug: string;
  name: string;
}

export interface ExtraEnvVar {
  key: string;
  value: string;
}

// Result of testing an extra API key against its SECRET_CHECK_* line in
// deploy.conf. Only "invalid" should stop a deploy — "unverified" means the
// service couldn't answer clearly (network, rate limit), not that the key is bad.
export interface SecretCheckResult {
  status: "ok" | "invalid" | "unverified" | "none";
  detail: string;
  host: string;
}

export interface CreateRequest {
  opsDir: string;
  appName: string;
  sshKeyName: string;
  tier: string;
  // Empty means "use deploy.conf's DROPLET_REGION"; otherwise overrides it
  // for this deploy only.
  region: string;
  autoYes: boolean;
  sqlUser: string;
  sqlPassword: string;
  gpgPassphrase: string;
  extraEnv: ExtraEnvVar[];
}

export interface DeleteRequest {
  opsDir: string;
  appName: string;
  backup: "yes" | "no" | "";
  sshKeyName: string;
  gpgPassphrase: string;
}

export interface RedeployRequest {
  opsDir: string;
  appName: string;
  backup: "yes" | "no" | "";
  sshKeyName: string;
  gpgPassphrase: string;
  forceRebuild: boolean;
}

// What `redeploy.sh --check` reports: whether the branch has code newer than
// what's deployed. "behind" means there's something new to ship; a redeploy is
// allowed in every state. commits is -1 when it couldn't be counted.
export interface RedeployCheck {
  state: "current" | "behind" | "unknown" | "no-app";
  deployed: string;
  latest: string;
  commits: number;
  branch: string;
  note: string;
  // "file: line" for each destructive SQL line the new commits add.
  destructiveSql: string[];
}

export const loadSettings = (): Promise<Settings> => Backend.LoadSettings();
export const setRememberSecrets = (remember: boolean): Promise<void> => Backend.SetRememberSecrets(remember);
export const loadSecrets = (extraNames: string[]): Promise<LoadedSecrets> =>
  Backend.LoadSecrets(extraNames) as Promise<LoadedSecrets>;
export const saveSecrets = (bundle: SecretsBundle): Promise<void> =>
  Backend.SaveSecrets(bundle as never);
export const forgetSecrets = (extraNames: string[]): Promise<void> => Backend.ForgetSecrets(extraNames);
export const checkExtraSecret = (
  opsDir: string,
  appName: string,
  envName: string,
  value: string,
): Promise<SecretCheckResult> => Backend.CheckExtraSecret(opsDir, appName, envName, value) as Promise<SecretCheckResult>;
// Tests a check spec that may not be saved yet (the Config tab's editor).
export const testSecretCheck = (spec: string, value: string): Promise<SecretCheckResult> =>
  Backend.TestSecretCheck(spec, value) as Promise<SecretCheckResult>;
export const getVersion = (): Promise<string> => Backend.GetVersion();
export const configuredSecretChecks =(opsDir: string, appName: string, envNames: string[]): Promise<string[]> =>
  Backend.ConfiguredSecretChecks(opsDir, appName, envNames);
export const getOpsDir =(): Promise<string> => Backend.GetOpsDir();
export const openOpsDir = (opsDir: string): Promise<void> => Backend.OpenOpsDir(opsDir);
export const listGames = (opsDir: string): Promise<string[]> => Backend.ListGames(opsDir);
export const selectApp = (appName: string): Promise<void> => Backend.SelectApp(appName);
export const setTheme = (theme: string): Promise<void> => Backend.SetTheme(theme);
export const hasBackups = (opsDir: string, appName: string): Promise<boolean> => Backend.HasBackups(opsDir, appName);
export const openBackupsFolder = (opsDir: string, appName: string): Promise<void> => Backend.OpenBackupsFolder(opsDir, appName);
export const deleteGame = (opsDir: string, appName: string): Promise<void> => Backend.DeleteGame(opsDir, appName);
export const renameGame = (opsDir: string, oldName: string, newName: string): Promise<void> =>
  Backend.RenameGame(opsDir, oldName, newName);

export const loadDeployConf = (opsDir: string, appName: string): Promise<DeployConfResult> =>
  Backend.LoadDeployConf(opsDir, appName);
export const createDeployConf = (opsDir: string, appName: string, conf: DeployConf): Promise<void> =>
  Backend.CreateDeployConf(opsDir, appName, conf as never);
export const saveDeployConf = (opsDir: string, appName: string, conf: DeployConf): Promise<void> =>
  Backend.SaveDeployConf(opsDir, appName, conf as never);

export const runPreflightChecks = (): Promise<PreflightResult> => Backend.RunPreflightChecks();
export const listSSHKeys = (opsDir: string): Promise<string[]> => Backend.ListSSHKeys(opsDir);
export const listAvailableTiers = (opsDir: string, appName: string, region: string): Promise<TierOption[]> =>
  Backend.ListAvailableTiers(opsDir, appName, region);
export const listAvailableRegions = (opsDir: string, appName: string): Promise<RegionOption[]> =>
  Backend.ListAvailableRegions(opsDir, appName);
export const openURL = (url: string): Promise<void> => Backend.OpenURL(url);
export const getBalance = (): Promise<BalanceResult> => Backend.GetBalance();
export const checkStatus = (appName: string): Promise<StatusResult> => Backend.CheckStatus(appName);

export const runCreate = (req: CreateRequest): Promise<void> => Backend.RunCreate(req as never);
export const runDelete = (req: DeleteRequest): Promise<void> => Backend.RunDelete(req as never);
export const runRedeploy = (req: RedeployRequest): Promise<void> => Backend.RunRedeploy(req as never);
export const checkRedeploy = (opsDir: string, appName: string): Promise<RedeployCheck> =>
  Backend.CheckRedeploy(opsDir, appName) as Promise<RedeployCheck>;
export const cancelRun = (appName: string): Promise<boolean> => Backend.CancelRun(appName);

// See app.go's CheckForUpdate/ApplyUpdate — this path is not yet verified
// end-to-end against a real tagged release.
export const checkForUpdate = (): Promise<UpdateInfo> => Backend.CheckForUpdate();
export const applyUpdate = (): Promise<void> => Backend.ApplyUpdate();

export function onLog(event: "create:log" | "delete:log" | "redeploy:log", handler: (line: LogLine) => void): void {
  EventsOn(event, handler);
}

export function onExit(event: "create:exit" | "delete:exit" | "redeploy:exit", handler: (info: ExitInfo) => void): void {
  EventsOn(event, handler);
}
