// Thin wrappers around the Wails-generated bindings in ../wailsjs/go/main/App
// (generated by `wails dev` / `wails build` — not checked in, see .gitignore).
// Keeping every backend call behind this module means the rest of the
// frontend never imports wailsjs directly.
import * as Backend from "../wailsjs/go/main/App";
import { EventsOn } from "../wailsjs/runtime/runtime";

export interface Settings {
  opsDir: string;
  lastGameRepoDir: string;
}

export interface DeployConf {
  appName: string;
  envPrefix: string;
  dbName: string;
  httpPort: string;
  gitRepo: string;
  gitUpstream: string;
  dropletRegion: string;
  dropletImage: string;
  dropletSize: string;
}

export interface DeployConfResult {
  found: boolean;
  conf: DeployConf;
}

export interface CheckResult {
  name: string;
  ok: boolean;
  detail: string;
}

export interface PreflightResult {
  wslBlocking: boolean;
  checks: CheckResult[];
}

export interface LogLine {
  stream: "stdout" | "stderr";
  text: string;
}

export interface ExitInfo {
  code: number;
  err?: string;
}

export interface CreateRequest {
  opsDir: string;
  gameRepoDir: string;
  sshKeyName: string;
  tier: string;
  autoYes: boolean;
  sqlUser: string;
  sqlPassword: string;
}

export interface DeleteRequest {
  opsDir: string;
  gameRepoDir: string;
  backup: "yes" | "no" | "";
}

export const loadSettings = (): Promise<Settings> => Backend.LoadSettings();
export const selectOpsDir = (): Promise<string> => Backend.SelectOpsDir();
export const selectGameRepoDir = (): Promise<string> => Backend.SelectGameRepoDir();
export const hasBackups = (gameRepoDir: string): Promise<boolean> => Backend.HasBackups(gameRepoDir);

export const loadDeployConf = (gameRepoDir: string): Promise<DeployConfResult> => Backend.LoadDeployConf(gameRepoDir);
export const createDeployConf = (opsDir: string, gameRepoDir: string, conf: DeployConf): Promise<void> =>
  Backend.CreateDeployConf(opsDir, gameRepoDir, conf);
export const saveDeployConf = (gameRepoDir: string, conf: DeployConf): Promise<void> =>
  Backend.SaveDeployConf(gameRepoDir, conf);

export const runPreflightChecks = (): Promise<PreflightResult> => Backend.RunPreflightChecks();
export const listSSHKeys = (): Promise<string[]> => Backend.ListSSHKeys();

export const runCreate = (req: CreateRequest): Promise<void> => Backend.RunCreate(req);
export const runDelete = (req: DeleteRequest): Promise<void> => Backend.RunDelete(req);
export const cancelRun = (): Promise<boolean> => Backend.CancelRun();

export function onLog(event: "create:log" | "delete:log", handler: (line: LogLine) => void): void {
  EventsOn(event, handler);
}

export function onExit(event: "create:exit" | "delete:exit", handler: (info: ExitInfo) => void): void {
  EventsOn(event, handler);
}
