// Thin wrappers around the Wails-generated bindings in ../wailsjs/go/main/App
// (generated by `wails dev` / `wails build` — not checked in, see .gitignore).
// Keeping every backend call behind this module means the rest of the
// frontend never imports wailsjs directly.
import * as Backend from "../wailsjs/go/main/App";
import { EventsOn } from "../wailsjs/runtime/runtime";

export interface Settings {
  lastAppName: string;
  theme: string;
}

export interface DeployConf {
  appName: string;
  envVarPrefix: string;
  dbName: string;
  httpPort: string;
  gitRepo: string;
  gitUpstream: string;
  gitBranch: string;
  dropletRegion: string;
  dropletImage: string;
  dropletSize: string;
  extraEnvVars: string;
}

export interface DeployConfResult {
  found: boolean;
  conf: DeployConf;
}

export interface CheckResult {
  name: string;
  ok: boolean;
  detail: string;
}

export interface PreflightResult {
  wslBlocking: boolean;
  checks: CheckResult[];
}

export interface LogLine {
  appName: string;
  stream: "stdout" | "stderr";
  text: string;
}

export interface ExitInfo {
  appName: string;
  code: number;
  err?: string;
}

export interface StatusResult {
  dropletExists: boolean;
  appExists: boolean;
  appURL: string;
}

export interface TierOption {
  number: number;
  slug: string;
  appSize: string;
  label: string;
}

export interface RegionOption {
  slug: string;
  name: string;
}

export interface CreateRequest {
  opsDir: string;
  appName: string;
  sshKeyName: string;
  tier: string;
  // Empty means "use deploy.conf's DROPLET_REGION"; otherwise overrides it
  // for this deploy only.
  region: string;
  autoYes: boolean;
  sqlUser: string;
  sqlPassword: string;
  gpgPassphrase: string;
  extraEnv: Record<string, string>;
}

export interface DeleteRequest {
  opsDir: string;
  appName: string;
  backup: "yes" | "no" | "";
  gpgPassphrase: string;
}

export const loadSettings = (): Promise<Settings> => Backend.LoadSettings();
export const getOpsDir = (): Promise<string> => Backend.GetOpsDir();
export const openOpsDir = (opsDir: string): Promise<void> => Backend.OpenOpsDir(opsDir);
export const listGames = (opsDir: string): Promise<string[]> => Backend.ListGames(opsDir);
export const selectApp = (appName: string): Promise<void> => Backend.SelectApp(appName);
export const setTheme = (theme: string): Promise<void> => Backend.SetTheme(theme);
export const hasBackups = (opsDir: string, appName: string): Promise<boolean> => Backend.HasBackups(opsDir, appName);
export const openBackupsFolder = (opsDir: string, appName: string): Promise<void> => Backend.OpenBackupsFolder(opsDir, appName);
export const deleteGame = (opsDir: string, appName: string): Promise<void> => Backend.DeleteGame(opsDir, appName);
export const renameGame = (opsDir: string, oldName: string, newName: string): Promise<void> =>
  Backend.RenameGame(opsDir, oldName, newName);

export const loadDeployConf = (opsDir: string, appName: string): Promise<DeployConfResult> =>
  Backend.LoadDeployConf(opsDir, appName);
export const createDeployConf = (opsDir: string, appName: string, conf: DeployConf): Promise<void> =>
  Backend.CreateDeployConf(opsDir, appName, conf);
export const saveDeployConf = (opsDir: string, appName: string, conf: DeployConf): Promise<void> =>
  Backend.SaveDeployConf(opsDir, appName, conf);

export const runPreflightChecks = (): Promise<PreflightResult> => Backend.RunPreflightChecks();
export const listSSHKeys = (): Promise<string[]> => Backend.ListSSHKeys();
export const listAvailableTiers = (opsDir: string, appName: string, region: string): Promise<TierOption[]> =>
  Backend.ListAvailableTiers(opsDir, appName, region);
export const listAvailableRegions = (opsDir: string, appName: string): Promise<RegionOption[]> =>
  Backend.ListAvailableRegions(opsDir, appName);
export const openURL = (url: string): Promise<void> => Backend.OpenURL(url);
export const checkStatus = (appName: string): Promise<StatusResult> => Backend.CheckStatus(appName);

export const runCreate = (req: CreateRequest): Promise<void> => Backend.RunCreate(req);
export const runDelete = (req: DeleteRequest): Promise<void> => Backend.RunDelete(req);
export const cancelRun = (appName: string): Promise<boolean> => Backend.CancelRun(appName);

export function onLog(event: "create:log" | "delete:log", handler: (line: LogLine) => void): void {
  EventsOn(event, handler);
}

export function onExit(event: "create:exit" | "delete:exit", handler: (info: ExitInfo) => void): void {
  EventsOn(event, handler);
}
